version: "3.7"

services:
  rstudio: 
    image: ajall1985/vast_dockerbuild 
    ports: 
      - "8787:8787"
    volumes:
      # Mount project folder on Box as a volume
      - ~/Box/Mills Lab/Projects/ForecastingChallenge:/home/rstudio/ForecastingChallenge
    env_file:
      - ./secret.env