version: "3.7"

services:
  rstudio: 
    image: ajall1985/vast_dockerbuild 
    ports: 
      - "8787:8787"
    volumes:
      - /Users/aallyn/GitHub/SDM-convergence:/home/rstudio/
    env_file:
      - ./secret.env